[package]
name = "experimented_lib"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
fs_extra = "1"
thiserror = "2.0.17"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
